elasticsearch:
  image: elasticsearch:2.0
  ports:
    - "9200:9200"
    - "9300:9300"
  command: "elasticsearch -Des.network.host=0.0.0.0"

kibana:
  image: kibana:4.2
  links:
    - elasticsearch:elasticsearch
  ports:
    - "5601:5601"

redis:
  image: redis

elastwitter:
  build: .
  command: "coffee elastweet.coffee"
  env_file: .env
  links:
    - redis:redis
    - elasticsearch:elasticsearch
  volumes:
    - $PWD:/usr/src/app

